#!/bin/bash

################################################################################
# PLATEFORME CRYPTO - ONE-LINER COMMANDS
# Copy & paste these commands to run tests
################################################################################

echo "🎯 PLATEFORME CRYPTO - COMMANDS CHEATSHEET"
echo ""

echo "═══════════════════════════════════════════════════════════"
echo "1️⃣  START API (Terminal 1)"
echo "═══════════════════════════════════════════════════════════"
echo ""
echo "cd /Users/guississ/Documents/GitHub/plateforme-crypto/backend && python main.py"
echo ""

echo "═══════════════════════════════════════════════════════════"
echo "2️⃣  RUN UNIT TESTS (Terminal 2)"
echo "═══════════════════════════════════════════════════════════"
echo ""
echo "# All tests"
echo "cd /Users/guississ/Documents/GitHub/plateforme-crypto/backend && pytest test_main.py -v"
echo ""
echo "# With coverage"
echo "cd /Users/guississ/Documents/GitHub/plateforme-crypto/backend && pytest test_main.py --cov=. --cov-report=html && open htmlcov/index.html"
echo ""
echo "# Specific test"
echo "cd /Users/guississ/Documents/GitHub/plateforme-crypto/backend && pytest test_main.py::TestAuthRegister -v"
echo ""

echo "═══════════════════════════════════════════════════════════"
echo "3️⃣  PERFORMANCE TESTS - LOCUST (Terminal 3)"
echo "═══════════════════════════════════════════════════════════"
echo ""
echo "# Web interface (interactive)"
echo "cd /Users/guississ/Documents/GitHub/plateforme-crypto/backend && locust -f locustfile.py --host=http://localhost:8000 --web"
echo "# Then open: http://localhost:8089"
echo ""
echo "# Headless (100 users, 10 min)"
echo "cd /Users/guississ/Documents/GitHub/plateforme-crypto/backend && locust -f locustfile.py --headless --users 100 --spawn-rate 10 --run-time 10m --csv=results/locust_100"
echo ""
echo "# Headless (200 users, stress)"
echo "cd /Users/guississ/Documents/GitHub/plateforme-crypto/backend && locust -f locustfile.py --headless --users 200 --spawn-rate 20 --run-time 15m --csv=results/locust_200"
echo ""

echo "═══════════════════════════════════════════════════════════"
echo "4️⃣  PERFORMANCE TESTS - K6 (Terminal 3)"
echo "═══════════════════════════════════════════════════════════"
echo ""
echo "# Full test (~23 min)"
echo "cd /Users/guississ/Documents/GitHub/plateforme-crypto/backend && k6 run loadtest_k6.js"
echo ""
echo "# Quick test (~3 min)"
echo "cd /Users/guississ/Documents/GitHub/plateforme-crypto/backend && k6 run loadtest_k6.js --stage 0s:0 --stage 1m:50 --stage 1m:100 --stage 1m:0"
echo ""
echo "# With JSON output"
echo "cd /Users/guississ/Documents/GitHub/plateforme-crypto/backend && k6 run loadtest_k6.js --out json=results/k6_results.json"
echo ""

echo "═══════════════════════════════════════════════════════════"
echo "5️⃣  CODE QUALITY ANALYSIS"
echo "═══════════════════════════════════════════════════════════"
echo ""
echo "# Full analysis"
echo "cd /Users/guississ/Documents/GitHub/plateforme-crypto && ./quality_analysis.sh"
echo ""
echo "# Pylint"
echo "cd /Users/guississ/Documents/GitHub/plateforme-crypto/backend && pylint main.py auth.py db.py"
echo ""
echo "# Flake8"
echo "cd /Users/guississ/Documents/GitHub/plateforme-crypto/backend && flake8 . --max-line-length=100"
echo ""
echo "# Bandit (security)"
echo "cd /Users/guississ/Documents/GitHub/plateforme-crypto/backend && bandit -r . -f json -o results/bandit.json"
echo ""

echo "═══════════════════════════════════════════════════════════"
echo "6️⃣  SONARQUBE (requires running SonarQube)"
echo "═══════════════════════════════════════════════════════════"
echo ""
echo "# Start SonarQube (Docker)"
echo "docker run -d --name sonarqube -p 9001:9000 sonarqube:latest"
echo ""
echo "# Run scan"
echo "cd /Users/guississ/Documents/GitHub/plateforme-crypto && sonar-scanner -Dsonar.projectKey=plateforme-crypto -Dsonar.sources=backend -Dsonar.host.url=http://localhost:9001 -Dsonar.token=squ_be8230eec593a304257e706480cd1d1187980965"
echo ""
echo "# View results"
echo "open http://localhost:9001/dashboard?id=plateforme-crypto"
echo ""

echo "═══════════════════════════════════════════════════════════"
echo "7️⃣  AUTOMATED SCRIPTS"
echo "═══════════════════════════════════════════════════════════"
echo ""
echo "# Interactive performance tests"
echo "cd /Users/guississ/Documents/GitHub/plateforme-crypto && ./run_performance_tests.sh"
echo ""
echo "# Locust mode"
echo "cd /Users/guississ/Documents/GitHub/plateforme-crypto && ./run_performance_tests.sh locust"
echo ""
echo "# k6 mode"
echo "cd /Users/guississ/Documents/GitHub/plateforme-crypto && ./run_performance_tests.sh k6"
echo ""

echo "═══════════════════════════════════════════════════════════"
echo "8️⃣  UTILITY COMMANDS"
echo "═══════════════════════════════════════════════════════════"
echo ""
echo "# Check if ports are in use"
echo "lsof -i :8000  # API"
echo "lsof -i :8089  # Locust web"
echo "lsof -i :9001  # SonarQube"
echo ""
echo "# Kill process on port"
echo "lsof -i :8000 | grep LISTEN | awk '{print \$2}' | xargs kill -9"
echo ""
echo "# Verify API is running"
echo "curl http://localhost:8000/health"
echo ""
echo "# View coverage report"
echo "open /Users/guississ/Documents/GitHub/plateforme-crypto/backend/htmlcov/index.html"
echo ""

echo "═══════════════════════════════════════════════════════════"
echo "📚 DOCUMENTATION FILES"
echo "═══════════════════════════════════════════════════════════"
echo ""
echo "# Quick start guide"
echo "open /Users/guississ/Documents/GitHub/plateforme-crypto/TESTS_QUICK_START.md"
echo ""
echo "# Complete execution guide"
echo "open /Users/guississ/Documents/GitHub/plateforme-crypto/EXECUTE_TESTS.md"
echo ""
echo "# Setup summary"
echo "open /Users/guississ/Documents/GitHub/plateforme-crypto/SETUP_COMPLETE.md"
echo ""
echo "# Performance tests guide"
echo "open /Users/guississ/Documents/GitHub/plateforme-crypto/PERFORMANCE_TESTS.md"
echo ""
echo "# Quality metrics"
echo "open /Users/guississ/Documents/GitHub/plateforme-crypto/QUALITY_METRICS.md"
echo ""

echo "═══════════════════════════════════════════════════════════"
echo "🚀 QUICK START (Copy & Run)"
echo "═══════════════════════════════════════════════════════════"
echo ""
echo "# Terminal 1:"
echo "cd /Users/guississ/Documents/GitHub/plateforme-crypto/backend && python main.py"
echo ""
echo "# Terminal 2:"
echo "cd /Users/guississ/Documents/GitHub/plateforme-crypto/backend && pytest test_main.py -v"
echo ""
echo "# Terminal 3:"
echo "cd /Users/guississ/Documents/GitHub/plateforme-crypto/backend && k6 run loadtest_k6.js --stage 0s:0 --stage 1m:50 --stage 1m:100 --stage 1m:0"
echo ""
echo "═══════════════════════════════════════════════════════════"
echo ""
