sonar.projectKey=plateforme-crypto
sonar.projectName=Plateforme Crypto
sonar.sources=backend,collector
sonar.tests=backend/tests,collector/tests
sonar.language=py
sonar.python.version=3.12

sonar.python.coverage.reportPaths=coverage.xml
sonar.sourceEncoding=UTF-8
