.PHONY: kind-up kind-down ingress load-images deploy delete

kind-up:
	./infra/kind-up.sh

kind-down:
	./infra/kind-down.sh

ingress:
	./infra/install-ingress.sh

load-images:
	./infra/load-images.sh

deploy:
	./infra/deploy.sh

delete:
	./infra/delete.sh
