apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - base
  - observability
  - backups
images:
  - name: plateforme-crypto-backend
    newName: ghcr.io/placeholder/plateforme-crypto-backend
    newTag: latest
  - name: plateforme-crypto-frontend
    newName: ghcr.io/placeholder/plateforme-crypto-frontend
    newTag: latest
  - name: plateforme-crypto-collector
    newName: ghcr.io/placeholder/plateforme-crypto-collector
    newTag: latest
